//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public int AttDetID { get; set; }
        public Nullable<int> AttID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Others { get; set; }
    
        public virtual Attendance Attendance { get; set; }
    }
}
